config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :users
  resources :posts do 
    resources :comments
    resources :upvotes, only: :create, controller: 'posts/upvotes'
    resources :downvotes, only: :create, controller: 'posts/downvotes'
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  # get "sessions/create"
  # get "sessions/destroy"
  # get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_one_attached :photo

  delegate :email, to: :user, prefix: true
  
  validates :photo, :description, presence: true
  

  acts_as_votable
end

app/controllers/posts/downvotes_controller.rb
class Posts::DownvotesController < ApplicationController
       def create
        @post = Post.find(params[:post_id])
        @post.downvote_from current_user if current_user
        
        # respond_to do |format|
        #     # format.turbo_stream { render turbo_stream: turbo_stream.replace("post_#{params[:post_id]}_container", partial: 'posts/likes', locals: { post: @post }) }
        #   format.turbo_stream { render turbo_stream: turbo_stream.replace("post_#{params[:post_id]}_container", partial: 'posts/likes', locals: { post: @post }) }
        # end

        respond_to do |format|
  format.turbo_stream {
    render turbo_stream: turbo_stream.replace(
      "post_#{params[:post_id]}_container",
      partial: 'posts/likes',
      locals: { post: @post }
    )
  }
  format.html { redirect_to posts_path } # fallback
end

    end
end

app/controllers/posts/upvotes_controller.rb
class Posts::UpvotesController < ApplicationController
    
    def create
        @post = Post.find(params[:post_id])
        @post.liked_by current_user if current_user

        # respond_to do |format|
        #     format.turbo_stream { render turbo_stream: turbo_stream.replace("post_#{params[:post_id]}_container", partial: 'posts/likes', locals: { post: @post }) }
        # end

        respond_to do |format|
  format.turbo_stream {
    render turbo_stream: turbo_stream.replace(
      "post_#{params[:post_id]}_container",
      partial: 'posts/likes',
      locals: { post: @post }
    )
  }
  format.html { redirect_to posts_path } # fallback
end

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user, only: [:new, :create]
    before_action :is_owner?, only: [:edit, :update, :destroy]

    def index
        @posts = Post.all.order('created_at DESC').includes(:user, comments: :user)    
    end

    def new
        @post = Post.new
    end

    def create 
        @post = current_user.posts.create(post_params)
        if @post.valid?
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        if @post.valid?
            redirect_to root_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to root_path
    end

    private

    def is_owner?
        redirect_to root_path if Post.find(params[:id]).user != current_user
    end

    def post_params
        params.require(:post).permit(:photo, :description)
    end
end

app/helpers/posts/downvotes_helper.rb
module Posts::DownvotesHelper
end

app/helpers/posts/upvotes_helper.rb
module Posts::UpvotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_likes.html.erb
<div class="px-2 py-4 flex gap-2" id="post_<%= post.id %>_container">
        <% if current_user.present? %>
          <% if current_user.voted_up_on? post %>
            <turbo-frame id="post_<%= post.id %>_container">
              <%= button_to post_downvotes_path(post),
                method: :post,
                data: { turbo_frame: "post_#{post.id}_container" } do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="red" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
              </svg>
            <% end %>
          </turbo-frame>
          <% else %>
          <turbo-frame id="post_<%= post.id %>_container">
            <%= button_to post_upvotes_path(post),
                method: :post,
                data: { turbo_frame: "post_#{post.id}_container" } do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
              </svg>
            <% end %>
          </turbo-frame>
          <% end %>

        <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12Z" />
          </svg>
        <% end %>
        <%= pluralize post.get_likes.size, "like" %>
</div>

app/views/posts/edit.html.erb
<h1 class="text-2xl mb-4 font-bold">Edit Post</h1>

<div class="md:w-[40%]">
  <%= simple_form_for @post do |f| %>
    <%= f.input :photo %>
    <%= f.input :description, input_html: { rows: 8 } %>
    <%= f.submit 'Update Post', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800' %>
  <% end %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="w-xl m-auto border-2" style="border-radius:10px">
    <!-- User info section -->
    <div>
      <%= image_tag post.user.photo if post.user.photo.attached? %>
    </div>

    <div class="font-dosis font-bold text-xl py-2 px-4 border-b-1 flex justify-between">
      <%= link_to user_name(post.user_email), user_path(post.user_id) %>
      
      <div>
        <%= link_to 'Edit', edit_post_path(post.id), 
                   class: 'py-2 px-3 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700' %>
          
        <%= link_to 'Delete', post_path(post.id), 
                   method: :delete, 
                   class: 'py-2 px-3 me-2 mb-2 text-sm font-medium text-white focus:outline-none bg-red-600 rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-red-700 dark:bg-red-800 dark:text-white-400 dark:border-red-600 dark:hover:text-white dark:hover:bg-red-700' %>
      </div>
    </div>

    <div class="w-xl h-xl">
      <%= image_tag post.photo, class: 'm-auto md:max-w-[75%]' %>
    </div>
    
    <div class="py-2 px-4 border-y-1 italic">
      <%= post.description %>
    </div>

    <% if post.user == current_user %>
      <!-- Likes section -->
      <%= render partial: 'likes', locals: { post: post } %>
      <!-- Comments list -->
      <% post.comments.each do |comment| %>
        <div class="px-6  text-base bg-white rounded-lg">
          <footer class="flex justify-between items-center p-2 rounded-lg mb-2">
            <div class="flex items-center justify-between">
              <p class="inline-flex items-center text-sm text-gray-600 dark:text-gray-600">
              <span class="font-semibold">
                <%= link_to user_name(comment.user_email), user_path(post.user_id) %>: &nbsp;
              </span>
                <%= comment.comment %>   
              </p>
            </div>
              
            <%= button_to 'Delete', 
                         post_comment_path(post, comment), 
                         method: :delete, 
                         class: 'text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-xs px-3 py-2 me-2  dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800' %>
          </footer>
        </div>
      <% end %>
    <% end %> 
      
      <!-- Comment form (styled version) -->
      <%= simple_form_for Comment.new, 
                          url: post_comments_path(post), 
                          method: :post, 
                          html: { class: "w-fit mb-4 mx-4" } do |f| %>
        <div class="px-4 py-1 bg-white rounded-lg dark:bg-gray-800">
          <%= f.input :comment,
                  as: :text,
                  label: false,
                  placeholder: "Write a comment...",
                  input_html: {
                    rows: 1,
                    id: "comment",
                    class: "w-full px-0 text-sm text-gray-900 bg-white border-0 dark:bg-gray-800 focus:ring-0 dark:text-white dark:placeholder-gray-400",
                    required: true
                  } %>
                  
                  <div class="flex items-center justify-between px-3 py-2 border-t dark:border-gray-600 border-gray-200">
                  <%= f.button :submit, "Post comment", 
                  class: "inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800" %>
                    </div>
                    </div>
      <% end %>
  </div> 
<% end %> 

app/views/posts/new.html.erb
<h1 class="text-2xl mb-4 font-bold">New Post</h1>

<div class="md:w-[40%]">
  <%= simple_form_for @post do |f| %>
    <%= f.input :photo %>
    <%= f.input :description, input_html: { rows: 8 } %>
    <%= f.submit 'Post', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800' %>
  <% end %>
</div>

app/views/posts/post.html.erb
<h1>Hello World</h1>